###
GET   http://localhost:3000/api/employess

###
POST  http://localhost:3000/api/employess
Content-Type: application/json

{
    "name": "Keren",
    "position": "CTO",
    "office": "Bogota",
    "salary": 40000
}

###
GET   http://localhost:3000/api/employess/5f7e2fb2225b500828c2be86

###
PUT  http://localhost:3000/api/employess/5f659925b3f0a5c6fb0ce66e
Content-Type: application/json

{
    "office": "Sincelejo"
}

###
DELETE  http://localhost:3000/api/employess/5f6591a28f0248a59d30beac

//Auth API

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "rogerex07",
    "email": "roger.mesa@test.com",
    "password": "271200",
    "roles": ["admin"]
}

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "roger@test.com",
    "password": "271200"
}
